### PR TITLE
Add attributes argument that support strings and objects

### PR DESCRIPTION
**Pull request by SeanMcP**
This PR adds an additional argument to the `heroicon` shortcodes for custom attributes. The attributes argument supports a string or an object (provided the templating language allows object arguments).

This should resolve the use cases identified in #4 without adding an infinite number of ordered arguments.

### CODE REVIEW

**Comment by andrewdisley** [comment]
This PR is good to ship. Thanks for this @SeanMcP

**Comment by SeanMcP** [comment]
@andrewdisley I'm going to add you as a repo collaborator so that you can review the PR and get noted as a contributor.

**Comment by andrewdisley** [comment]
Thanks @SeanMcP merged, not sure on the process for publishing so will let you update package.json.

It is a non-breaking change, so suggest 1.1.0 as version as heroicons v2.0.0 was recently released it might be an idea to track same version. I will get a PR in for initial heroicons v2 support excluding mini as I have that working locally with just a slight tweak on the build.js

**Comment by SeanMcP** [comment]
@andrewdisley Sounds great! I created #6 to keep track of any development discussions.

**Pull request merged**
